### ISSUE TITLE
unnecessary dependency Dumbbench

### ISSUE THREAD

**Issue by karenetheridge** [glasswalk3r/archive-tar-wrapper-perl#14]
Dumbbench doesn't install cleanly on more recent perls; could this dependency be removed?  I would suggest moving t/008performance.t to xt/ so it doesn't run for normal installations.

**Comment by glasswalk3r** [comment]
Fixed with release 0.37, already uploaded to CPAN.

**Comment by karenetheridge** [comment]
thanks very much!
