### ISSUE TITLE
Test::Simple should not be a runtime dependency

### ISSUE THREAD

**Issue by oschwald** [glasswalk3r/archive-tar-wrapper-perl#6]
With the release of 0.27, [Test::Simple is a runtime dependency](https://metacpan.org/source/ARFREITAS/Archive-Tar-Wrapper-0.27/META.json#L41). This is particularly an issue for us as it pulls in Test2, which our test runner is not yet compatible with.

**Comment by glasswalk3r** [comment]
Test2 is not a requirement, but at least a version of `Test::Simple` which contains `is_deeply` (from Test::More package) is.
I made some changes on 6069aa8d443bd1bc45743c56dab02406ba24333e that might or not help you, depending on the version of `ExtUtils::MakeMaker` that you have available.
Please evaluate, if didn't help you, please provide the version of Test::Simple you have available (remembering the requirements already described).

**Comment by oschwald** [comment]
This appears better to me. Thanks!
