### ISSUE TITLE
no recent Changes entries

### ISSUE THREAD

**Issue by karenetheridge** [glasswalk3r/archive-tar-wrapper-perl#7]
There are no Changes entries for the 0.27, 0.28 or 0.29 releases.

**Comment by glasswalk3r** [comment]
Being hard to keep record of changes and fixing long time known bugs... I just forget to do it.
I'm considering migrating the distribution to Dist::Zilla, integrate the Changelog with the git log and forgetting about doing it manually.
For now I'll keep this issue opened as a reminder to do it ASAP.

**Comment by glasswalk3r** [comment]
It's going to be hard to use Dist::Zilla, since there are some tests that the module needs to execute when running over Microsoft Windows (and deciding that the OS is supported after all).

After two years, I think it's safe to keep updating CHANGELOG instead, so I'm closing this one.

**Comment by karenetheridge** [comment]
> It's going to be hard to use Dist::Zilla, since there are some tests that the module needs to execute when running over Microsoft Windows

Do you need to check the OS in Makefile.PL, or just in tests? if the latter, then `plan skip_all => 'These tests are for MSWin32 only' if $^O ne 'MSWin32';` should suffice. If the former, come hit me (or others) up on irc.perl.org/#dist-zilla and we can help you find the right syntax for build time.
